### ISSUE TITLE
Is Optional Bundle Identifier?

### ISSUE THREAD

**Issue by techinpark** [rogerluan/app-store-connect-notifier#14]
In `fetch_app_status.rb`  using environment for `bundle_identifier` 

```
bundle_id = ENV["BUNDLE_IDENTIFIER"]
```

but , in `README.md`  has no content.

**Comment by rogerluan** [comment]
Oh! Great catch, that's my bad - merely poor documentation. I'll fix the README, to also include the `BUNDLE_IDENTIFIER`, just like the Heroku config file already enforces 💪 

Thanks for catching this, @techinpark !

**Comment by rogerluan** [comment]
Just to clarify: the `BUNDLE_IDENTIFIER` is a required environment variable. Please set it 🙏 

The PR is up and will be merged once it passes CI 🎉 thanks again for reporting this issue!
