### ISSUE TITLE
Play Store Support

### ISSUE THREAD

**Issue by johnf** [rogerluan/app-store-connect-notifier#197]
@rogerluan Would you have any interest in extending this at all to perform similar actions for the Google play store?
Asking before I do a PR, otherwise I'll fork and create a sibling project that just does the google bits

**Comment by johnf** [comment]
Never mind, did some research and there are no APIs to do this.

**Comment by rogerluan** [comment]
Hi @johnf 👋 

Shame to hear it's not possible, but thanks for your interest to extend the functionality of this package :)
