### ISSUE TITLE
Feature request: Track multiple apps

### ISSUE THREAD

**Issue by AdityaAnand1** [rogerluan/app-store-connect-notifier#84]

**Comment by rogerluan** [comment]
This would be a great feature! Way better than creating multiple instances. How do you envision the interface of this @AdityaAnand1 ?

**Comment by AdityaAnand1** [comment]
I think having multiple values for environment variables would be the most painless way to implement + use this.

By default, just one value is accepted, for multiple apps - provide comma separated env variable values.

**Comment by rogerluan** [comment]
Hm, that's not a bad idea. One requirement for users would be that the values would have to be in the right order (envvar[1] and anotherenvvar[1] must match the same app, and so forth). Not terrible.

Another way would be a json config file such as:

```js
{
    "apps": [
        {
            "env_var_1": "value",
            "env_var_2": "value",
        },
        {
            "env_var_1": "value",
            "env_var_2": "value",
        }
    ]
}
```

Not sure what's the best way to load that into env vars, though (taking Heroku as the main target environment)

**Comment by rogerluan** [comment]
@AdityaAnand1 this was implemented in https://github.com/rogerluan/app-store-connect-notifier/pull/143 and will be released soon  🚀

**Comment by rogerluan** [comment]
This was released in https://github.com/rogerluan/app-store-connect-notifier/releases/tag/v2.1.0 🚀
